### ISSUE TITLE
Libretro core build error on x86_64 Linux

### ISSUE THREAD

**Issue by Sanaki** [stella-emu/stella#808]
Bisect result:
c73261b7168b76245ae2e91e86d73d07b7e35db7 is the first bad commit

make error (from c8463ae54b075fb40da9e30bfd28db53f866d636):
```
g++ -I. -I.. -I../libretro -I../emucore -I../emucore/tia -I../common -I../common/audio -I../common/tv_filters -I../common/repository/sqlite -I../json -I../sqlite   -std=c++17 -fno-rtti -DGIT_VERSION=\"" c8463ae54"\" -flto -O3 -DNDEBUG  -Wall -W -Wno-unused-parameter -fPIC -D__LIB_RETRO__ -DSOUND_SUPPORT -DHAVE_STDINT_H -DHAVE_STRINGS_H -fno-rtti -pedantic -c -o../emucore/Thumbulator.o ../emucore/Thumbulator.cxx
distcc[9094] ERROR: compile (null) on localhost failed
../emucore/Thumbulator.cxx:77:5: warning: multi-line comment [-Wcomment]
   77 |     //FETCH_TYPE(CycleType::N, AccessType::data); \
      |     ^
../emucore/Thumbulator.cxx:82:5: warning: multi-line comment [-Wcomment]
   82 |     //FETCH_TYPE(CycleType::N, AccessType::data); \
      |     ^
../emucore/Thumbulator.cxx: In member function ‘int Thumbulator::execute()’:
../emucore/Thumbulator.cxx:1246:7: error: ‘INC_SHIFT_CYCLES’ was not declared in this scope; did you mean ‘INC_I_CYCLES’?
 1246 |       INC_SHIFT_CYCLES;
      |       ^~~~~~~~~~~~~~~~
      |       INC_I_CYCLES
../emucore/Thumbulator.cxx:1287:7: error: ‘INC_SHIFT_CYCLES’ was not declared in this scope; did you mean ‘INC_I_CYCLES’?
 1287 |       INC_SHIFT_CYCLES;
      |       ^~~~~~~~~~~~~~~~
      |       INC_I_CYCLES
../emucore/Thumbulator.cxx:1890:47: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
 1890 |             INC_S_CYCLES(sp, AccessType::data);
      |                                               ^
../emucore/Thumbulator.cxx:2093:7: error: ‘INC_SHIFT_CYCLES’ was not declared in this scope; did you mean ‘INC_I_CYCLES’?
 2093 |       INC_SHIFT_CYCLES;
      |       ^~~~~~~~~~~~~~~~
      |       INC_I_CYCLES
../emucore/Thumbulator.cxx:2126:7: error: ‘INC_SHIFT_CYCLES’ was not declared in this scope; did you mean ‘INC_I_CYCLES’?
 2126 |       INC_SHIFT_CYCLES;
      |       ^~~~~~~~~~~~~~~~
      |       INC_I_CYCLES
../emucore/Thumbulator.cxx:2150:7: error: ‘INC_SHIFT_CYCLES’ was not declared in this scope; did you mean ‘INC_I_CYCLES’?
 2150 |       INC_SHIFT_CYCLES;
      |       ^~~~~~~~~~~~~~~~
      |       INC_I_CYCLES
../emucore/Thumbulator.cxx:2183:7: error: ‘INC_SHIFT_CYCLES’ was not declared in this scope; did you mean ‘INC_I_CYCLES’?
 2183 |       INC_SHIFT_CYCLES;
      |       ^~~~~~~~~~~~~~~~
      |       INC_I_CYCLES
../emucore/Thumbulator.cxx:2342:47: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
 2342 |             INC_S_CYCLES(sp, AccessType::data);
      |                                               ^
../emucore/Thumbulator.cxx:2413:47: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
 2413 |             INC_S_CYCLES(rd, AccessType::data);
      |                                               ^
../emucore/Thumbulator.cxx:2510:7: error: ‘INC_SHIFT_CYCLES’ was not declared in this scope; did you mean ‘INC_I_CYCLES’?
 2510 |       INC_SHIFT_CYCLES;
      |       ^~~~~~~~~~~~~~~~
      |       INC_I_CYCLES
../emucore/Thumbulator.cxx:2577:47: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
 2577 |             INC_S_CYCLES(sp, AccessType::data);
      |                                               ^
../emucore/Thumbulator.cxx:2596:7: error: ‘INC_STR_CYCLES’ was not declared in this scope; did you mean ‘INC_S_CYCLES’?
 2596 |       INC_STR_CYCLES;
      |       ^~~~~~~~~~~~~~
      |       INC_S_CYCLES
../emucore/Thumbulator.cxx:2609:7: error: ‘INC_STR_CYCLES’ was not declared in this scope; did you mean ‘INC_S_CYCLES’?
 2609 |       INC_STR_CYCLES;
      |       ^~~~~~~~~~~~~~
      |       INC_S_CYCLES
../emucore/Thumbulator.cxx:2623:7: error: ‘INC_STR_CYCLES’ was not declared in this scope; did you mean ‘INC_S_CYCLES’?
 2623 |       INC_STR_CYCLES;
      |       ^~~~~~~~~~~~~~
      |       INC_S_CYCLES
../emucore/Thumbulator.cxx:2651:7: error: ‘INC_STRB_CYCLES’ was not declared in this scope; did you mean ‘INC_LDRB_CYCLES’?
 2651 |       INC_STRB_CYCLES;
      |       ^~~~~~~~~~~~~~~
      |       INC_LDRB_CYCLES
../emucore/Thumbulator.cxx:2679:7: error: ‘INC_STRB_CYCLES’ was not declared in this scope; did you mean ‘INC_LDRB_CYCLES’?
 2679 |       INC_STRB_CYCLES;
      |       ^~~~~~~~~~~~~~~
      |       INC_LDRB_CYCLES
../emucore/Thumbulator.cxx:2693:7: error: ‘INC_STR_CYCLES’ was not declared in this scope; did you mean ‘INC_S_CYCLES’?
 2693 |       INC_STR_CYCLES;
      |       ^~~~~~~~~~~~~~
      |       INC_S_CYCLES
../emucore/Thumbulator.cxx:2706:7: error: ‘INC_STR_CYCLES’ was not declared in this scope; did you mean ‘INC_S_CYCLES’?
 2706 |       INC_STR_CYCLES;
      |       ^~~~~~~~~~~~~~
      |       INC_S_CYCLES
Makefile:634: recipe for target '../emucore/Thumbulator.o' failed
make: *** [../emucore/Thumbulator.o] Error 1
```

**Comment by Sanaki** [comment]
Doesn't seem to have made a difference unfortunately.

**Comment by thrust26** [comment]
Hm, for me the latest build shows 'passed'. @Sanaki What is still wrong with it?

**Comment by Sanaki** [comment]
Bugger, I think the continued issue was local. Sorry about that. Did a manual checkout of origin/master to bypass a merge conflict and it compiled fine after your fix.
