### ISSUE TITLE
I can't compile.

### ISSUE THREAD

**Issue by Csokis** [stella-emu/stella#734]
I can't compile on xubuntu 20.04.1. :(

> ─csokis@csokisPC /mnt/minden/Sources/stella ‹master› 
╰─$ make                                                                                        2 ↵
mkdir -p -p src/gui/.deps
mkdir -p -p out/src/gui
g++ -MMD -MF "src/gui/.deps/FileListWidget.d" -MQ "out/src/gui/FileListWidget.o" -MP -O2 -x c++ -Wall -Wextra -Wno-unused-parameter -Wno-multichar -Wunused -Woverloaded-virtual -Wnon-virtual-dtor -std=c++14 -fomit-frame-pointer -DSDL_SUPPORT -D_GLIBCXX_USE_CXX11_ABI=1 -DUNIX -DBSPF_UNIX -DGUI_SUPPORT -DWINDOWED_SUPPORT -DSOUND_SUPPORT -DDEBUGGER_SUPPORT -DJOYSTICK_SUPPORT -DCHEATCODE_SUPPORT -DPNG_SUPPORT -DZIP_SUPPORT  -Isrc/emucore -Isrc/common -Isrc/common/tv_filters -Isrc/emucore/tia -Isrc/emucore/tia/frame-manager -I/usr/include/SDL2 -D_REENTRANT -Isrc/unix -Isrc/gui -Isrc/debugger -Isrc/debugger/gui -Isrc/yacc -Isrc/cheat -c src/gui/FileListWidget.cxx -o out/src/gui/FileListWidget.o
src/gui/FileListWidget.cxx: In member function ‘void FileListWidget::setLocation(const FilesystemNode&, const string&)’:
src/gui/FileListWidget.cxx:78:25: error: using typedef-name ‘using CancelCheck = const class std::function<bool()>’ after ‘class’
   78 |   class FilesystemNode::CancelCheck isCancelled = []() {
      |                         ^~~~~~~~~~~
In file included from src/gui/FileListWidget.hxx:24,
                 from src/gui/FileListWidget.cxx:21:
src/emucore/FSNode.hxx:60:11: note: ‘using CancelCheck = const class std::function<bool()>’ has a previous declaration here
   60 |     using CancelCheck = std::function<bool()> const;
      |           ^~~~~~~~~~~
src/gui/FileListWidget.cxx:80:3: error: invalid user-defined conversion from ‘FileListWidget::setLocation(const FilesystemNode&, const string&)::<lambda()>’ to ‘int’ [-fpermissive]
   80 |   };
      |   ^
src/gui/FileListWidget.cxx:78:51: note: candidate is: ‘FileListWidget::setLocation(const FilesystemNode&, const string&)::<lambda()>::operator bool (*)()() const’ <near match>
   78 |   class FilesystemNode::CancelCheck isCancelled = []() {
      |                                                   ^
src/gui/FileListWidget.cxx:78:51: note:   no known conversion from ‘bool (*)()’ to ‘int’
src/gui/FileListWidget.cxx:91:61: error: cannot convert ‘int’ to ‘FilesystemNode::CancelCheck&’ {aka ‘const std::function<bool()>&’}
   91 |     _node.getAllChildren(_fileList, _fsmode, _filter, true, isCancelled);
      |                                                             ^~~~~~~~~~~
      |                                                             |
      |                                                             int
In file included from src/gui/FileListWidget.hxx:24,
                 from src/gui/FileListWidget.cxx:21:
src/emucore/FSNode.hxx:128:44: note:   initializing argument 5 of ‘bool FilesystemNode::getAllChildren(FSList&, FilesystemNode::ListMode, const NameFilter&, bool, FilesystemNode::CancelCheck&) const’
  128 |                         const CancelCheck& isCancelled = []() { return false; }) const;
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/gui/FileListWidget.cxx:96:65: error: cannot convert ‘int’ to ‘FilesystemNode::CancelCheck&’ {aka ‘const std::function<bool()>&’}
   96 |     _node.getChildren(_fileList, _fsmode, _filter, false, true, isCancelled);
      |                                                                 ^~~~~~~~~~~
      |                                                                 |
      |                                                                 int
In file included from src/gui/FileListWidget.hxx:24,
                 from src/gui/FileListWidget.cxx:21:
src/emucore/FSNode.hxx:141:41: note:   initializing argument 6 of ‘bool FilesystemNode::getChildren(FSList&, FilesystemNode::ListMode, const NameFilter&, bool, bool, FilesystemNode::CancelCheck&) const’
  141 |                      const CancelCheck& isCancelled = []() { return false; }) const;
      |                      ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/gui/FileListWidget.cxx: In member function ‘virtual std::string FileListWidget::getToolTip(const Common::Point&) const’:
src/gui/FileListWidget.cxx:258:41: warning: comparison of integer expressions of different signedness: ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  258 |   if(_includeSubDirs && _dirList.size() > idx)
      |                         ~~~~~~~~~~~~~~~~^~~~~
make: *** [Makefile:256: out/src/gui/FileListWidget.o] Error 1

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/2db6ab7d1646ee5848ee725bea9c375ade747a72.

**Comment by thrust26** [comment]
It is crazy the Visual Studio compiles wrong code without errors. 😠

**Comment by sa666666** [comment]
Absolutely true.  But in this case I think you didn't pull https://github.com/stella-emu/stella/commit/53f24729fdad9fd4075d007a935c54f86d42426c, which already fixed part of this issue.
